version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  prepare:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - package.json
            - LICENSE
            - README.md
  test:
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run ci
      - store_test_results:
          path: test-results
workflows:
  build-and-test:
    jobs:
      - prepare
      - build:
          requires:
            - test
      - test:
          requires:
            - prepare